server:
  port: 9090

spring:
  application:
    name: aws_project02

management:
  endpoints:
    web:
      exposure:
        include: health,info

aws:
  region: us-east-1
  sqs:
    queue:
      product:
        events:
          name: product-events